import Foundation

public enum L10n {
    private static let russian: [String: String] = [
        "appName": "NotesApp",
        "library": "Библиотека",
        "allNotes": "Все заметки",
        "trash": "Корзина",
        "tags": "Теги",
        "notes": "Заметки",
        "search": "Поиск",
        "searchPlaceholder": "Найти заметку…",
        "newNote": "Новая заметка",
        "newTag": "Новый тег",
        "noNotes": "Заметок нет",
        "noNotesHint": "Создайте первую заметку или измените фильтр.",
        "selectNote": "Выберите заметку",
        "selectNoteHint": "Выберите заметку в списке или создайте новую.",
        "untitled": "Без названия",
        "save": "Сохранить",
        "saved": "Все изменения сохранены",
        "unsaved": "Есть несохранённые изменения",
        "delete": "Удалить",
        "deletePermanently": "Удалить навсегда",
        "restore": "Восстановить",
        "pin": "Закрепить",
        "unpin": "Открепить",
        "addTag": "Добавить тег",
        "removeTag": "Убрать тег",
        "changeColor": "Изменить цвет",
        "tagName": "Название тега",
        "create": "Создать",
        "cancel": "Отмена",
        "close": "Закрыть",
        "sort": "Сортировка",
        "recentFirst": "Сначала недавние",
        "oldestFirst": "Сначала старые",
        "titleAscending": "Название А–Я",
        "titleDescending": "Название Я–А",
        "createdNewest": "Сначала новые",
        "createdOldest": "Сначала давно созданные",
        "settings": "Настройки",
        "general": "Основные",
        "appearance": "Оформление",
        "theme": "Тема",
        "system": "Системная",
        "light": "Светлая",
        "dark": "Тёмная",
        "font": "Шрифт редактора",
        "fontSize": "Размер шрифта",
        "autoSave": "Автосохранение",
        "defaultSorting": "Сортировка по умолчанию",
        "language": "Язык",
        "russian": "Русский",
        "english": "Английский",
        "reset": "Сбросить",
        "storage": "Хранилище",
        "chooseStorage": "Выбрать папку хранения…",
        "storageHint": "Можно открыть папку из Windows-версии с notes.db и файлами note-XXXXXX.md.",
        "currentFolder": "Текущая папка",
        "bold": "Жирный",
        "italic": "Курсив",
        "heading": "Заголовок",
        "checklist": "Чек-лист",
        "toggleChecklist": "Отметить пункт",
        "table": "Таблица",
        "tableEditor": "Редактор таблицы",
        "tableMarkdownHint": "Изменения сохраняются как обычная Markdown-таблица",
        "rows": "Строки",
        "columns": "Столбцы",
        "addRowAbove": "Добавить строку выше",
        "addRowBelow": "Добавить строку ниже",
        "deleteRow": "Удалить строку",
        "moveRowUp": "Переместить строку вверх",
        "moveRowDown": "Переместить строку вниз",
        "addColumnLeft": "Добавить столбец слева",
        "addColumnRight": "Добавить столбец справа",
        "deleteColumn": "Удалить столбец",
        "moveColumnLeft": "Переместить столбец влево",
        "moveColumnRight": "Переместить столбец вправо",
        "alignment": "Выравнивание",
        "alignLeft": "По левому краю",
        "alignCenter": "По центру",
        "alignRight": "По правому краю",
        "alignDefault": "По умолчанию",
        "headerRow": "Шапка",
        "columnHeader": "Заголовок",
        "defaultColumn": "Столбец",
        "cellValue": "Значение",
        "tableSize": "%d × %d",
        "tableKeyboardHint": "Enter переходит к следующей ячейке; в конце создаётся новая строка.",
        "apply": "Применить",
        "editTable": "Редактировать таблицу",
        "insertTable": "Вставить таблицу",
        "tasks": "Задачи",
        "completedTasks": "Выполнено %d из %d",
        "noTasks": "В заметке нет задач",
        "source": "Исходник",
        "livePreview": "Визуально",
        "reading": "Чтение",
        "editorMode": "Режим редактора",
        "saveMarkdown": "Сохранить Markdown",
        "rename": "Переименовать…",
        "duplicate": "Дублировать",
        "revealFinder": "Показать в Finder",
        "moveTrash": "Переместить в корзину",
        "noteActions": "Действия с заметкой",
        "strikethrough": "Зачёркнутый",
        "highlight": "Выделение",
        "bulletList": "Маркированный список",
        "numberedList": "Нумерованный список",
        "task": "Задача",
        "toggleTask": "Переключить задачу",
        "blockquote": "Цитата",
        "inlineCode": "Строчный код",
        "codeBlock": "Блок кода",
        "markdownLink": "Markdown-ссылка",
        "wikilink": "Вики-ссылка",
        "attachFiles": "Прикрепить файлы",
        "find": "Найти",
        "selectMarkdownNote": "Выберите Markdown-заметку",
        "fileFirstHint": "Заметки — обычные UTF-8 файлы в текущем vault.",
        "createNote": "Создать заметку",
        "unsavedMarkdown": "Markdown не сохранён",
        "wordsCount": "%d слов",
        "charactersCount": "%d символов",
        "editMarkdown": "Редактировать текст",
        "visualPreviewHint": "Таблицы и задачи работают как визуальные элементы",
        "files": "Файлы",
        "markdownFilesCount": "%d Markdown-файлов",
        "noMarkdownNotes": "Нет Markdown-заметок",
        "searchFilesPaths": "Поиск по названиям, содержимому и путям",
        "newFolder": "Новая папка",
        "openVault": "Открыть vault…",
        "createVault": "Создать vault…",
        "revealVault": "Показать vault в Finder",
        "rebuildManifest": "Пересобрать реестр файлов",
        "rebuildSearchIndex": "Пересобрать поисковый индекс",
        "vaultActions": "Действия с vault",
        "newNoteHere": "Новая заметка здесь",
        "newFolderHere": "Новая папка здесь",
        "openVaultTitle": "Открытие vault",
        "createVaultTitle": "Создание vault",
        "ok": "OK",
        "externalConflict": "Внешнее изменение файла",
        "reloadDisk": "Загрузить версию с диска",
        "overwriteMine": "Перезаписать моей версией",
        "keepEditing": "Продолжить редактирование",
        "removedExternalMessage": "Файл был удалён вне NotesApp. Загрузка с диска закроет редактор; перезапись станет доступна после повторного создания файла.",
        "changedExternalMessage": "Заметка изменилась вне NotesApp, пока у вас были несохранённые правки. Выберите версию, которую нужно сохранить.",
        "moveItemTrashQuestion": "Переместить объект в корзину?",
        "name": "Название",
        "outline": "Структура",
        "outgoingLinks": "Исходящие ссылки",
        "backlinks": "Обратные ссылки",
        "noHeadings": "Нет заголовков",
        "noLinks": "Нет ссылок",
        "noBacklinks": "Нет обратных ссылок",
        "outlineLinksSummary": "Структура и ссылки · %d / %d / %d",
        "autoSaveMarkdown": "Автосохранение Markdown",
        "filesSettings": "Файлы",
        "vault": "Vault",
        "migration": "Миграция",
        "newNotes": "Новые заметки",
        "vaultRoot": "Корень vault",
        "specifiedFolder": "Указанная папка",
        "folderRelativeVault": "Папка относительно vault",
        "attachments": "Вложения",
        "sameFolderAsNote": "Та же папка, что и заметка",
        "subfolderNextToNote": "Подпапка рядом с заметкой",
        "subfolderName": "Название подпапки",
        "saveVaultSettings": "Сохранить настройки vault",
        "currentMarkdownVault": "Текущий Markdown-vault",
        "noVault": "Vault не открыт",
        "openAnotherVault": "Открыть другой vault…",
        "notesappMetadataHint": "Папка `.notesapp` содержит только восстанавливаемые настройки и метаданные кэша. Источником истины остаются Markdown-файлы.",
        "legacyMigration": "Миграция SQLite / RTF",
        "legacyMigrationHint": "Исходная база открывается только для чтения. Импорт сначала создаёт согласованную резервную копию SQLite, затем записывает новые Markdown-файлы и никогда не удаляет исходные данные.",
        "activeCount": "%d активных",
        "deletedCount": "%d удалённых",
        "tagsCount": "%d тегов",
        "noLegacyStore": "Старое хранилище не выбрано.",
        "chooseLegacyFolder": "Выбрать старую папку…",
        "dryRun": "Пробный запуск",
        "backupImport": "Создать копию и импортировать",
        "undoLastImport": "Отменить последний импорт",
        "reportItems": "Отчёт: %d объектов",
        "refreshDisk": "Обновить с диска",
        "revealSelected": "Показать выбранный объект в Finder",
        "duplicateSelected": "Дублировать выбранную заметку",
        "moveSelectedTrash": "Переместить выбранную заметку в корзину",
        "rebuildingIndex": "Пересборка поискового индекса…",
        "indexingProgress": "Индексируется %d из %d…",
        "indexRebuilt": "Индекс пересобран из Markdown-файлов.",
        "indexingCancelled": "Индексирование отменено.",
        "updatingIndex": "Обновление индекса…",
        "indexUpToDate": "Индекс актуален.",
        "legacyStoreFound": "Найдено старое хранилище: %d заметок.",
        "analyzingMigration": "Анализ миграции…",
        "backingUpImporting": "Создание резервной копии и импорт…",
        "dryRunComplete": "Пробный запуск завершён: можно импортировать %d заметок.",
        "migrationComplete": "Миграция завершена: импортировано %d, уже было %d, ошибок %d.",
        "checkingUndo": "Проверка импортированных файлов перед отменой…",
        "undoComplete": "При отмене %d неизменённых файлов перемещено в восстанавливаемую папку `.notesapp/migration-undo`; %d отредактированных файлов сохранено.",
        "ambiguousLink": "Неоднозначная ссылка",
        "ambiguousLinkMatches": "%@ соответствует:\n%@",
        "pastedImage": "Вставленное изображение",
        "migrationStatus.planned": "запланировано",
        "migrationStatus.imported": "импортировано",
        "migrationStatus.skippedAlreadyImported": "уже импортировано",
        "migrationStatus.failed": "ошибка",
        "internalLink": "Внутренняя ссылка",
        "insertLink": "Вставить ссылку",
        "openLink": "Открыть ссылку",
        "uppercase": "В верхний регистр",
        "lowercase": "В нижний регистр",
        "format": "Формат",
        "error": "Ошибка",
        "databaseError": "Не удалось открыть хранилище",
        "deleteNoteQuestion": "Удалить заметку «%@»?",
        "deleteTagQuestion": "Удалить тег «%@»?",
        "permanentWarning": "Это действие нельзя отменить.",
        "linkNotFound": "Заметка «%@» не найдена.",
        "noLinkableNotes": "Нет других заметок для ссылки.",
        "created": "Создано",
        "updated": "Изменено",
        "items": "%d заметок"
    ]

    private static let english: [String: String] = [
        "appName": "NotesApp",
        "library": "Library",
        "allNotes": "All Notes",
        "trash": "Trash",
        "tags": "Tags",
        "notes": "Notes",
        "search": "Search",
        "searchPlaceholder": "Search notes…",
        "newNote": "New Note",
        "newTag": "New Tag",
        "noNotes": "No notes",
        "noNotesHint": "Create your first note or change the filter.",
        "selectNote": "Select a note",
        "selectNoteHint": "Select a note in the list or create a new one.",
        "untitled": "Untitled",
        "save": "Save",
        "saved": "All changes saved",
        "unsaved": "Unsaved changes",
        "delete": "Delete",
        "deletePermanently": "Delete Permanently",
        "restore": "Restore",
        "pin": "Pin",
        "unpin": "Unpin",
        "addTag": "Add Tag",
        "removeTag": "Remove Tag",
        "changeColor": "Change Color",
        "tagName": "Tag name",
        "create": "Create",
        "cancel": "Cancel",
        "close": "Close",
        "sort": "Sort",
        "recentFirst": "Recent first",
        "oldestFirst": "Oldest first",
        "titleAscending": "Title A–Z",
        "titleDescending": "Title Z–A",
        "createdNewest": "Newest created",
        "createdOldest": "Oldest created",
        "settings": "Settings",
        "general": "General",
        "appearance": "Appearance",
        "theme": "Theme",
        "system": "System",
        "light": "Light",
        "dark": "Dark",
        "font": "Editor font",
        "fontSize": "Font size",
        "autoSave": "Auto-save",
        "defaultSorting": "Default sorting",
        "language": "Language",
        "russian": "Russian",
        "english": "English",
        "reset": "Reset",
        "storage": "Storage",
        "chooseStorage": "Choose storage folder…",
        "storageHint": "You can open a Windows-version folder containing notes.db and note-XXXXXX.md files.",
        "currentFolder": "Current folder",
        "bold": "Bold",
        "italic": "Italic",
        "heading": "Heading",
        "checklist": "Checklist",
        "toggleChecklist": "Toggle checklist item",
        "table": "Table",
        "tableEditor": "Table Editor",
        "tableMarkdownHint": "Changes are stored as a normal Markdown table",
        "rows": "Rows",
        "columns": "Columns",
        "addRowAbove": "Insert row above",
        "addRowBelow": "Insert row below",
        "deleteRow": "Delete row",
        "moveRowUp": "Move row up",
        "moveRowDown": "Move row down",
        "addColumnLeft": "Insert column left",
        "addColumnRight": "Insert column right",
        "deleteColumn": "Delete column",
        "moveColumnLeft": "Move column left",
        "moveColumnRight": "Move column right",
        "alignment": "Alignment",
        "alignLeft": "Align left",
        "alignCenter": "Align center",
        "alignRight": "Align right",
        "alignDefault": "Default alignment",
        "headerRow": "Header",
        "columnHeader": "Column heading",
        "defaultColumn": "Column",
        "cellValue": "Value",
        "tableSize": "%d × %d",
        "tableKeyboardHint": "Enter advances to the next cell and creates a row at the end.",
        "apply": "Apply",
        "editTable": "Edit table",
        "insertTable": "Insert table",
        "tasks": "Tasks",
        "completedTasks": "%d of %d completed",
        "noTasks": "This note has no tasks",
        "source": "Source",
        "livePreview": "Visual",
        "reading": "Reading",
        "editorMode": "Editor mode",
        "saveMarkdown": "Save Markdown",
        "rename": "Rename…",
        "duplicate": "Duplicate",
        "revealFinder": "Reveal in Finder",
        "moveTrash": "Move to Trash",
        "noteActions": "Note actions",
        "strikethrough": "Strikethrough",
        "highlight": "Highlight",
        "bulletList": "Bullet list",
        "numberedList": "Numbered list",
        "task": "Task",
        "toggleTask": "Toggle task",
        "blockquote": "Blockquote",
        "inlineCode": "Inline code",
        "codeBlock": "Code block",
        "markdownLink": "Markdown link",
        "wikilink": "Wikilink",
        "attachFiles": "Attach files",
        "find": "Find",
        "selectMarkdownNote": "Select a Markdown note",
        "fileFirstHint": "Notes are ordinary UTF-8 files in the current vault.",
        "createNote": "Create note",
        "unsavedMarkdown": "Unsaved Markdown",
        "wordsCount": "%d words",
        "charactersCount": "%d characters",
        "editMarkdown": "Edit text",
        "visualPreviewHint": "Tables and tasks work as visual elements",
        "files": "Files",
        "markdownFilesCount": "%d Markdown files",
        "noMarkdownNotes": "No Markdown notes",
        "searchFilesPaths": "Search names, contents, and paths",
        "newFolder": "New folder",
        "openVault": "Open vault…",
        "createVault": "Create vault…",
        "revealVault": "Reveal vault in Finder",
        "rebuildManifest": "Rebuild file manifest",
        "rebuildSearchIndex": "Rebuild search index",
        "vaultActions": "Vault actions",
        "newNoteHere": "New note here",
        "newFolderHere": "New folder here",
        "openVaultTitle": "Open Vault",
        "createVaultTitle": "Create Vault",
        "ok": "OK",
        "externalConflict": "External file conflict",
        "reloadDisk": "Reload disk version",
        "overwriteMine": "Overwrite with my version",
        "keepEditing": "Keep editing",
        "removedExternalMessage": "The file was removed outside NotesApp. Reload closes this editor; overwrite is available only after recreating the file.",
        "changedExternalMessage": "This note changed outside NotesApp while your version had unsaved edits. Choose which version to keep.",
        "moveItemTrashQuestion": "Move item to Trash?",
        "name": "Name",
        "outline": "Outline",
        "outgoingLinks": "Outgoing",
        "backlinks": "Backlinks",
        "noHeadings": "No headings",
        "noLinks": "No links",
        "noBacklinks": "No backlinks",
        "outlineLinksSummary": "Outline & links · %d / %d / %d",
        "autoSaveMarkdown": "Auto-save Markdown",
        "filesSettings": "Files",
        "vault": "Vault",
        "migration": "Migration",
        "newNotes": "New notes",
        "vaultRoot": "Vault root",
        "specifiedFolder": "Specified folder",
        "folderRelativeVault": "Folder relative to vault",
        "attachments": "Attachments",
        "sameFolderAsNote": "Same folder as note",
        "subfolderNextToNote": "Subfolder next to note",
        "subfolderName": "Subfolder name",
        "saveVaultSettings": "Save vault settings",
        "currentMarkdownVault": "Current Markdown vault",
        "noVault": "No vault",
        "openAnotherVault": "Open another vault…",
        "notesappMetadataHint": "The `.notesapp` folder contains only replaceable settings and cache metadata. Markdown files remain the source of truth.",
        "legacyMigration": "Legacy SQLite / RTF migration",
        "legacyMigrationHint": "The source database is opened read-only. Import first creates a consistent SQLite backup, writes new Markdown files, and never removes the original data.",
        "activeCount": "%d active",
        "deletedCount": "%d deleted",
        "tagsCount": "%d tags",
        "noLegacyStore": "No legacy store selected.",
        "chooseLegacyFolder": "Choose legacy folder…",
        "dryRun": "Dry run",
        "backupImport": "Back up and import",
        "undoLastImport": "Undo last import",
        "reportItems": "Report: %d items",
        "refreshDisk": "Refresh from disk",
        "revealSelected": "Reveal selected item in Finder",
        "duplicateSelected": "Duplicate selected note",
        "moveSelectedTrash": "Move selected note to Trash",
        "rebuildingIndex": "Rebuilding search index…",
        "indexingProgress": "Indexing %d of %d…",
        "indexRebuilt": "Index rebuilt from Markdown files.",
        "indexingCancelled": "Indexing cancelled.",
        "updatingIndex": "Updating index…",
        "indexUpToDate": "Index is up to date.",
        "legacyStoreFound": "Legacy store found: %d notes.",
        "analyzingMigration": "Analyzing migration…",
        "backingUpImporting": "Backing up and importing…",
        "dryRunComplete": "Dry run complete: %d notes can be imported.",
        "migrationComplete": "Migration complete: %d imported, %d already present, %d failed.",
        "checkingUndo": "Checking imported files before undo…",
        "undoComplete": "Undo moved %d unchanged files into recoverable `.notesapp/migration-undo`; %d edited files were kept.",
        "ambiguousLink": "Ambiguous link",
        "ambiguousLinkMatches": "%@ matches:\n%@",
        "pastedImage": "Pasted image",
        "migrationStatus.planned": "planned",
        "migrationStatus.imported": "imported",
        "migrationStatus.skippedAlreadyImported": "already imported",
        "migrationStatus.failed": "failed",
        "internalLink": "Internal Link",
        "insertLink": "Insert Link",
        "openLink": "Open Link",
        "uppercase": "Uppercase",
        "lowercase": "Lowercase",
        "format": "Format",
        "error": "Error",
        "databaseError": "Could not open storage",
        "deleteNoteQuestion": "Delete “%@”?",
        "deleteTagQuestion": "Delete tag “%@”?",
        "permanentWarning": "This action cannot be undone.",
        "linkNotFound": "Note “%@” was not found.",
        "noLinkableNotes": "There are no other notes to link.",
        "created": "Created",
        "updated": "Updated",
        "items": "%d notes"
    ]

    public static func text(_ key: String, language: AppLanguage) -> String {
        let table = language == .english ? english : russian
        return table[key] ?? russian[key] ?? key
    }

    public static func format(_ key: String, language: AppLanguage, _ arguments: CVarArg...) -> String {
        String(format: text(key, language: language), locale: Locale.current, arguments: arguments)
    }
}
